#!/bin/sh
SERVICE='ssl' 
if ps ax | grep -v grep | grep $SERVICE > /dev/null
then
    echo "$SERVICE ssl running, everything is fine"
else
    echo "$SERVICE is not running"
    echo "$SERVICE is not running!" 
fi
